version: '3'

services:
  # Client
  rfid-client:
    image: abiosoft/caddy
    container_name: rfid-client
    restart: unless-stopped
    volumes:
      - ./client:/srv
    ports:
      - "80:2015"

  # WebService - NodeJS
  rfid-server:
    image: ambientum/node
    container_name: rfid-server
    command: node index.js
    restart: unless-stopped
    volumes:
      - ./server/nodejs:/var/www/app
    ports:
      - "3000:3000"
    links:
      - rfid-mysql
    depends_on:
      - rfid-mysql

  # MySQL (5.7)
  rfid-mysql:
    image: ambientum/mysql:5.7
    container_name: rfid-mysql
    restart: unless-stopped
    volumes:
      - ./rfid-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rfid
      - MYSQL_USER=rfid
      - MYSQL_PASSWORD=rfid

  rfid-mqtt:
    image: eclipse-mosquitto
    container_name: rfid-mqtt
    restart: unless-stopped
    volumes:
      - ./rfid-mqtt/config:/mosquitto/config
      - ./rfid-mqtt/data:/mosquitto/data
      - ./rfid-mqtt/log:/mosquitto/log  
    ports:
      - "1883:1883"
      - "9001:9001"

  phpmyadmin:
    container_name: phpmyadmin
    image: bitnami/phpmyadmin:latest
    restart: unless-stopped
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/Recife
    ports:
      - 443:443
    labels:
      kompose.service.type: nodeport
    volumes:
      - ./phpmyadmin_data:/bitnami
